module.exports.products = require('./products')
module.exports.vouchers = require('./vouchers')
module.exports.customers = require('./customers')
module.exports.deliveries = require('./deliveries')
module.exports.orders = require('./orders')
