version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: install
          command: npm install
      - run:
          name: lint
          command: npm run lint
      - run:
          name: test
          command: npm run test
      - run:
          name: compile
          command: node compile.js
      # - run:
      #     name: test
      #     command: npm test
      # - run: npm run coverage
      # - run: git describe --exact-match --tags HEAD && npm run docs && npm run deploy-docs

      - run:
          name: Create service account creds
          command: |
            echo "$FIREBASE_SERVICE_ACCOUNT_CREDS_JSON" > "${HOME}/gcloud-service-key.json"
            echo 'export GOOGLE_APPLICATION_CREDENTIALS="$HOME/gcloud-service-key.json"' >> "$BASH_ENV"

      - run:
          name: release
          command: npm run semantic-release || true

workflows:
  version: 2
  build-and-release:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
