module.exports.carts = require('./carts')
module.exports.products = require('./products')
module.exports.registers = require('./registers')
module.exports.delivery_notes = require('./delivery_notes')
module.exports.configurations = require('./configurations')
module.exports.templates = require('./templates')
module.exports.transactions = require('./transactions')
module.exports.balances = require('./balances')
module.exports.discounts = require('./discounts')
// hygen:injection -  Please, don't delete this line: when running the cli for schema resources the new routes will be automatically added here.
