module.exports.balances = require('./balances')
module.exports.branches = require('./branches')
module.exports.carts = require('./carts')
module.exports.configurations = require('./configurations')
module.exports.customers = require('./customers')
module.exports.delivery_notes = require('./delivery_notes')
module.exports.discounts = require('./discounts')
module.exports.gastro_orders = require('./gastro_orders')
module.exports.products = require('./products')
module.exports.registers = require('./registers')
module.exports.templates = require('./templates')
module.exports.transactions = require('./transactions')
module.exports.statuses = require('./statuses')
module.exports.promotions = require('./promotions')

// hygen:injection -  Please, don't delete this line: when running the cli for schema resources the new routes will be automatically added here.
