const base = require('./base')

module.exports.request = {
  $id: 'https://schemas.tillhub.com/v0/favourites.create.request.schema.json',
  $schema: 'http://json-schema.org/draft-07/schema#',
  additionalProperties: false,
  required: [
    'name',
    'client_id' // TODO this should probably be generated by the API if missing
  ],
  properties: base,
  type: 'object'
}
