module.exports.create = require('./create')
module.exports.patch = require('./patch')
module.exports.incrementOrDecrement = require('./increment-or-decrement')
module.exports.get = require('./get')
module.exports.customers = require('./customers')
module.exports.bulk = require('./bulk')
