module.exports.create = require('./create')
module.exports.read = require('./read')
module.exports.update = require('./update')
module.exports.duplicate = require('./duplicate')
module.exports.availableTables = require('./available_tables')
